name: Nix flake lock update
description: Opinionated Nix flake lock update action

inputs:
  app-id:
    description: ID of the GitHub App.
    required: true
  private-key:
    description: Private key of the GitHub App (can be Base64 encoded).
    required: true
  path:
    description: >
      Relative path under $GITHUB_WORKSPACE to the repository.
      Defaults to $GITHUB_WORKSPACE.
  committer:
    description: >
      The committer name and email address in the format `Display Name <email@address.com>`.
      Defaults to 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'.
    default: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
  author:
    description: >
      The author name and email address in the format `Display Name <email@address.com>`.
      Defaults to 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'.
    default: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
  signoff:
    description: 'Add `Signed-off-by` line by the committer at the end of the commit log message.'
    default: false
  branch:
    description: 'The pull request branch name.'
    default: 'build/update-flake-lock'
  delete-branch:
    description: >
      Delete the `branch` when closing pull requests, and when undeleted after merging.
      Recommend `true`.
    default: false
  base:
    description: >
      The pull request base branch.
      Defaults to the branch checked out in the workflow.
  push-to-fork:
    description: >
      A fork of the checked out parent repository to which the pull request branch will be pushed.
      e.g. `owner/repo-fork`.
      The pull request will be created to merge the fork's branch into the parent's base.
  title:
    description: 'The title of the pull request.'
    default: 'build(nix): update dependencies'
  labels:
    description: 'A comma or newline separated list of labels.'
  assignees:
    description: 'A comma or newline separated list of assignees (GitHub usernames).'
  reviewers:
    description: 'A comma or newline separated list of reviewers (GitHub usernames) to request a review from.'
  team-reviewers:
    description: >
      A comma or newline separated list of GitHub teams to request a review from.
  milestone:
    description: 'The number of the milestone to associate the pull request with.'
  draft:
    description: 'Create a draft pull request. It is not possible to change draft status after creation except through the web interface'
    default: false

runs:
  using: composite
  steps:
    - id: app-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.private-key }}

    - uses: actions/checkout@v4

    - uses: DeterminateSystems/nix-installer-action@v13

    - name: Update flake lock
      id: update
      shell: bash
      run: |
        git config user.name github-actions[bot]
        git config user.email github-actions[bot]@users.noreply.github.com

        tip=$(git rev-parse HEAD)
        nix flake update --commit-lock-file --commit-lock-file-summary 'build(nix): update dependencies'

        if [ $tip != $(git rev-parse HEAD) ]; then
          echo "updated=true" >> $GITHUB_OUTPUT

          echo "UPDATED_INPUTS<<EOF" >> $GITHUB_ENV
          git log --format=%b -n 1 | tail -n +3 >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

          git reset HEAD^
        fi

    - uses: peter-evans/create-pull-request@v6
      id: cpr
      if: ${{ steps.update.outputs.updated == 'true' }}
      with:
        assignees: ${{ inputs.assignees }}
        author: ${{ inputs.author }}
        base: ${{ inputs.base }}
        body: |
          ## Description

          Automated Nix flake update

          ## Changes

          ```
          ${{ env.UPDATED_INPUTS }}
          ```
        branch: ${{ inputs.branch }}
        commit-message: |
          build(nix): update dependencies

          ${{ env.UPDATED_INPUTS }}
        committer: ${{ inputs.committer }}
        delete-branch: ${{ inputs.delete-branch }}
        draft: ${{ inputs.draft }}
        labels: ${{ inputs.labels }}
        milestone: ${{ inputs.milestone }}
        path: ${{ inputs.path }}
        push-to-fork: ${{ inputs.push-to-fork }}
        reviewers: ${{ inputs.reviewers }}
        signoff: ${{ inputs.signoff }}
        team-reviewers: ${{ inputs.team-reviewers }}
        title: ${{ inputs.title }}
        token: ${{ steps.app-token.outputs.token }}
